version: "3.9"
services:
  bot:
    build:
      context: .
    env_file:
      - .env
    container_name: csihu
    depends_on:
      - db
  db:
    image: postgres:14.5-alpine3.16
    container_name: csihu-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
