[flake8]
ignore = "E402"
max-line-length = 88

[tool.isort]
profile = "black"

[tool.poetry]
name = "csihu"
version = "2.0.0"
description = "A bot that is used for the CompsSci Discord Server"
authors = ["Vitaman02"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Vitaman02/CS-IHU-NotifierBot"

[tool.poetry.dependencies]
python = "^3.10"
discord = "2.0.0"
python-dotenv = "^0.20.0"
requests = "2.28.1"

[tool.poetry.dev-dependencies]
black = "22.6.0"
flake8 = "5.0.4"
pre-commit = "2.20.0"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/Vitaman02/CS-IHU-NotifierBot/issues"
"CI/CD" = "https://github.com/Vitaman02/CS-IHU-NotifierBot/actions"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
