[tool.isort]
profile = "black"

[tool.poetry]
name = "csihu"
version = "3.3.0"
description = "A bot that is used for the CompsSci Discord Server"
authors = ["atbuy <buy@atbuy.dev>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/atbuy/csihu-notificator"

[tool.poetry.dependencies]
python = "^3.10"
python-urbandict = "^0.3.10"
discord-py = "^2.4.0"
beautifulsoup4 = "4.12.3"
lxml = "5.3.0"
SQLAlchemy = {extras = ["asyncio"], version = "1.4.47"}
asyncpg = "0.30.0"
pydantic = "2.10.3"
alembic = "1.14.0"
pygsearch = "0.5.1"
cchardet = "2.2.0a2"
selenium = "4.27.1"
pydantic-settings = "^2.7.0"
prometheus-async = "^22.2.0"
aiohttp = "^3.11.10"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/atbuy/csihu-notificator/issues"
"CI/CD" = "https://github.com/atbuy/csihu-notificator/actions"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.8.0"
ruff = "^0.6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
