[flake8]
ignore = "E402"
max-line-length = 88

[tool.isort]
profile = "black"

[tool.poetry]
name = "csihu"
version = "3.0.2"
description = "A bot that is used for the CompsSci Discord Server"
authors = ["atbuy"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/atbuy/CS-IHU-NotifierBot"

[tool.poetry.dependencies]
python = "^3.10"
discord = "2.0.0"
requests = "^2.31.0"
python-urbandict = "0.2.5"
beautifulsoup4 = "4.12.0"
lxml = "4.9.2"
SQLAlchemy = {extras = ["asyncio"], version = "1.4.47"}
asyncpg = "0.26.0"
pydantic = "1.10.7"
alembic = "1.10.2"
pygsearch = "0.5.1"
cchardet = "2.1.7"
selenium = "4.8.3"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/atbuy/CS-IHU-NotifierBot/issues"
"CI/CD" = "https://github.com/atbuy/CS-IHU-NotifierBot/actions"

[tool.poetry.group.dev.dependencies]
isort = "5.12.0"
black = "23.3.0"
flake8 = "6.0.0"
pre-commit = "3.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
