[tool.flake8]
ignore = "E402"
max-line-length = 88

[tool.isort]
profile = "black"

[tool.poetry]
name = "csihu"
version = "3.1.0"
description = "A bot that is used for the CompsSci Discord Server"
authors = ["atbuy <contact.atbuy@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/atbuy/csihu-notificator"

[tool.poetry.dependencies]
python = "^3.10"
discord = "2.3.2"
requests = "^2.31.0"
python-urbandict = "0.3.2"
beautifulsoup4 = "4.12.0"
lxml = "4.9.3"
SQLAlchemy = {extras = ["asyncio"], version = "1.4.47"}
asyncpg = "0.26.0"
pydantic = "2.3.0"
alembic = "1.11.3"
pygsearch = "0.5.1"
cchardet = "2.1.7"
selenium = "4.8.3"
pydantic-settings = "^2.0.3"
prometheus-async = "^22.2.0"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/atbuy/csihu-notificator/issues"
"CI/CD" = "https://github.com/atbuy/csihu-notificator/actions"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
black = "^23.3.0"
flake8 = "^6.0.0"
pre-commit = "^3.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
